ignore-failures:
    python:
      - pyserial
additional-deps:
  python:
    # name can be included so Deadpendency can load the package details in the registry
    - name: asyncua
      repo: FreeOpcUa/opcua-asyncio
    - name: lxml
      repo: lxml/lxml
