openapi: 3.0.2
info:
  title: Flowchem - flowchem_config
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /elite11-1/pump/:
    get:
      tags:
      - elite11-1
      - elite11-1
      summary: Get Metadata
      operationId: get_metadata_elite11_1_pump__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /elite11-1/pump/infuse:
    put:
      tags:
      - elite11-1
      - elite11-1
      summary: Infuse
      description: Infuse.
      operationId: infuse_elite11_1_pump_infuse_put
      parameters:
      - required: false
        schema:
          title: Rate
          type: string
          default: ''
        name: rate
        in: query
      - required: false
        schema:
          title: Volume
          type: string
          default: ''
        name: volume
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /elite11-1/pump/stop:
    put:
      tags:
      - elite11-1
      - elite11-1
      summary: Stop
      description: Stops pump.
      operationId: stop_elite11_1_pump_stop_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /elite11-1/pump/is-pumping:
    get:
      tags:
      - elite11-1
      - elite11-1
      summary: Is Pumping
      description: True if pump is moving.
      operationId: is_pumping_elite11_1_pump_is_pumping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /elite11-1/pump/withdraw:
    put:
      tags:
      - elite11-1
      - elite11-1
      summary: Withdraw
      description: Withdraw.
      operationId: withdraw_elite11_1_pump_withdraw_put
      parameters:
      - required: false
        schema:
          title: Rate
          type: string
          default: 1 ml/min
        name: rate
        in: query
      - required: false
        schema:
          title: Volume
          type: string
        name: volume
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ComponentInfo:
      title: ComponentInfo
      required:
      - hw_device
      type: object
      properties:
        hw_device:
          $ref: '#/components/schemas/DeviceInfo'
        name:
          title: Name
          type: string
          default: ''
        owl_subclass_of:
          title: Owl Subclass Of
          type: string
          default: http://purl.obolibrary.org/obo/OBI_0000968
      description: Metadata associated with flowchem components.
    DeviceInfo:
      title: DeviceInfo
      required:
      - authors
      - maintainers
      - manufacturer
      - model
      type: object
      properties:
        authors:
          title: Authors
          type: array
          items:
            $ref: '#/components/schemas/Person'
        maintainers:
          title: Maintainers
          type: array
          items:
            $ref: '#/components/schemas/Person'
        manufacturer:
          title: Manufacturer
          type: string
        model:
          title: Model
          type: string
        additional_info:
          title: Additional Info
          type: object
          default: {}
        backend:
          title: Backend
          type: string
          default: flowchem v. 0.1.0a3
        serial_number:
          title: Serial Number
          type: string
          default: unknown
        version:
          title: Version
          type: string
          default: ''
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Person:
      title: Person
      required:
      - name
      - email
      type: object
      properties:
        name:
          title: Name
          type: string
        email:
          title: Email
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
