openapi: 3.1.0
info:
  title: 'Flowchem - '
  description: Flowchem is a library to control instruments and devices commonly found
    in chemistry labs via an interoperable web API.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0a3
paths:
  /my-EPC/:
    get:
      tags:
      - my-EPC
      summary: Get Device Info
      operationId: get_device_info_fake_device__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
  /my-EPC/EPC/:
    get:
      tags:
      - my-EPC
      - my-EPC
      summary: Get Component Info
      description: Return metadata.
      operationId: get_component_info_fake_device_EPC__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /my-EPC/EPC/power-on:
    put:
      tags:
      - my-EPC
      - my-EPC
      summary: Power On
      description: 'Power on the sensor.


        Returns:

        --------

        None'
      operationId: power_on_fake_device_EPC_power_on_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /my-EPC/EPC/power-off:
    put:
      tags:
      - my-EPC
      - my-EPC
      summary: Power Off
      description: 'Power off the sensor.


        Returns:

        --------

        None'
      operationId: power_off_fake_device_EPC_power_off_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /my-EPC/EPC/read-pressure:
    get:
      tags:
      - my-EPC
      - my-EPC
      summary: Read Pressure
      description: "Read the current pressure from the sensor and return it in the\
        \ specified units.\n\nParameters:\n-----------\nunits : str, optional\n  \
        \  The units in which to return the pressure (default is bar).\n\nReturns:\n\
        --------\nfloat\n    The current pressure in the specified units."
      operationId: read_pressure_fake_device_EPC_read_pressure_get
      parameters:
      - name: units
        in: query
        required: false
        schema:
          type: string
          default: bar
          title: Units
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /my-EPC/EPC/get-pressure:
    get:
      tags:
      - my-EPC
      - my-EPC
      summary: Get Pressure
      description: "Get the current system pressure in bar.\n\nReturns:\n--------\n\
        float\n    The current pressure in bar."
      operationId: get_pressure_fake_device_EPC_get_pressure_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: number
                title: Response Get Pressure Fake Device Epc Get Pressure Get
  /my-EPC/EPC/set-pressure:
    put:
      tags:
      - my-EPC
      - my-EPC
      summary: Set Pressure Setpoint
      description: "Set the controlled pressure to the instrument; default unit is\
        \ bar.\n\nParameters:\n-----------\npressure : str\n    The desired pressure\
        \ to set.\n\nReturns:\n--------\nbool\n    True if the pressure setpoint was\
        \ set successfully."
      operationId: set_pressure_setpoint_fake_device_EPC_set_pressure_put
      parameters:
      - name: pressure
        in: query
        required: true
        schema:
          type: string
          title: Pressure
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: boolean
                title: Response Set Pressure Setpoint Fake Device Epc Set Pressure
                  Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /my-EPC/EPC/stop:
    put:
      tags:
      - my-EPC
      - my-EPC
      summary: Stop
      description: "Stop the pressure controller by setting pressure to 0 bar.\n\n\
        Returns:\n--------\nbool\n    True if the pressure controller was stopped\
        \ successfully."
      operationId: stop_fake_device_EPC_stop_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: boolean
                title: Response Stop Fake Device Epc Stop Put
components:
  schemas:
    ComponentInfo:
      properties:
        name:
          type: string
          title: Name
          default: ''
        parent_device:
          type: string
          title: Parent Device
          default: ''
        type:
          type: string
          title: Type
          default: ''
        owl_subclass_of:
          items:
            type: string
          type: array
          title: Owl Subclass Of
          default:
          - http://purl.obolibrary.org/obo/OBI_0000968
      type: object
      title: ComponentInfo
      description: Metadata associated with flowchem components.
    DeviceInfo:
      properties:
        manufacturer:
          type: string
          title: Manufacturer
          default: ''
        model:
          type: string
          title: Model
          default: ''
        version:
          type: string
          title: Version
          default: ''
        serial_number:
          anyOf:
          - type: string
          - type: integer
          title: Serial Number
          default: unknown
        components:
          additionalProperties:
            type: string
            minLength: 1
            format: uri
          type: object
          title: Components
          default: {}
        backend:
          type: string
          title: Backend
          default: flowchem v. 1.0.0a3
        authors:
          items:
            type: string
            format: name-email
          type: array
          title: Authors
          default: []
        additional_info:
          type: object
          title: Additional Info
          default: {}
      type: object
      title: DeviceInfo
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
